"""修改document表

Revision ID: cb06cde5c060
Revises: 6a690bd1e827
Create Date: 2026-08-29 16:51:33.874868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb06cde5c060'
down_revision: Union[str, None] = '6a690bd1e827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment='对话标题',
               existing_nullable=True)
    op.alter_column('conversations', 'thread_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='线程ID',
               existing_nullable=False)
    op.alter_column('conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.add_column('documents', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='documentstatus'), nullable=True, comment='状态'))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True, comment='处理时间'))
    op.add_column('documents', sa.Column('celery_task_id', sa.String(length=100), nullable=True, comment='Celery任务ID'))
    op.alter_column('documents', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户ID',
               existing_nullable=False)
    op.alter_column('documents', 'file_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='文件名',
               existing_nullable=False)
    op.alter_column('documents', 'file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment='文件路径',
               existing_nullable=True)
    op.alter_column('documents', 'file_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='文件类型',
               existing_nullable=True)
    op.alter_column('documents', 'file_size',
               existing_type=mysql.INTEGER(display_width=11),
               comment='文件大小',
               existing_nullable=True)
    op.alter_column('documents', 'chunk_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='分块数量',
               existing_nullable=True)
    op.alter_column('documents', 'vector_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='向量ID',
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True)
    op.alter_column('messages', 'conversation_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='对话ID',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment='角色',
               existing_nullable=False)
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(),
               comment='消息内容',
               existing_nullable=False)
    op.alter_column('messages', 'tool_calls',
               existing_type=mysql.JSON(),
               comment='工具调用',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment='用户名',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment='邮箱',
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='全名',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否活跃',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='修改时间',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='修改时间',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否活跃',
               existing_nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='全名',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='用户名',
               existing_nullable=False)
    op.alter_column('messages', 'tool_calls',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='工具调用',
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='消息内容',
               existing_nullable=False)
    op.alter_column('messages', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='角色',
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='对话ID',
               existing_nullable=False)
    op.alter_column('documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('documents', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('documents', 'vector_id',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='向量ID',
               existing_nullable=True)
    op.alter_column('documents', 'chunk_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='分块数量',
               existing_nullable=True)
    op.alter_column('documents', 'file_size',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='文件大小',
               existing_nullable=True)
    op.alter_column('documents', 'file_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='文件类型',
               existing_nullable=True)
    op.alter_column('documents', 'file_path',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='文件路径',
               existing_nullable=True)
    op.alter_column('documents', 'file_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='文件名',
               existing_nullable=False)
    op.alter_column('documents', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.drop_column('documents', 'celery_task_id')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'status')
    op.alter_column('conversations', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True)
    op.alter_column('conversations', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversations', 'thread_id',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='线程ID',
               existing_nullable=False)
    op.alter_column('conversations', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='对话标题',
               existing_nullable=True)
    op.alter_column('conversations', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    # ### end Alembic commands ###
